### ISSUE TITLE
Tech Debt or Code Quality Category? 

### ISSUE THREAD

**Issue by etagwerker** [Maximization/nodejs-toolbox-catalog#1]
Hi there, 

I know this might be controversial, but I recently went looking for "tech debt" packages and I couldn't find any well-maintained packages out there. 

Here are a few that could be relevant: 

- ESLint - has rules that can identify usage of deprecated or obsolete API calls for a specific version of the Node runtime
- npm-check - checks for outdated, incorrect/missing, and unused dependencies. Categorizes updates by SemVer difference into Patch, Minor, Major updates.
- depngn - Scan package dependencies that include an engines field to determine compatibility with a specific version of Node runtime
- ES6-Plato is a tool for generating static code analysis reports for ECMAScript 2015 (ES6) and beyond. It uses the Plato library to generate code complexity visualizations and reports based on the AST (Abstract Syntax Tree) generated by the Esprima parser.
- code-complexity.  This tool supports several different complexity metrics, and also reports on the churn (total number of commits) on a file to evaluate hot spots.

Is there any interest in adding such a category? 

Please let me know.

Thanks!

**Comment by Maximization** [comment]
Thanks for the suggestions! Those packages would be a nice addition to the list.

In terms of categories, I think these libraries fall under these categories: code linters (eslint, also: typescript-eslint, jshint, rome, etc.), code metrics (es6-plato, code-complexity) and dependency management (npm-check, depngn, also: npm-check-updates, depcheck).

Feel free to open a PR and I'll review & merge on Monday.

**Comment by Maximization** [comment]
@etagwerker Added three new categories:

- [Code Complexity](https://nodejstoolbox.com/categories/code-complexity)
- [Code Linters](https://nodejstoolbox.com/categories/code-linters)
- [Dependency Management](https://nodejstoolbox.com/categories/dependency-management)
