### ISSUE TITLE
Add web scraping category 

### ISSUE THREAD

**Issue by mouad-mahfoud** [Maximization/nodejs-toolbox-catalog#10]
Add web scraping category.

**Comment by Maximization** [comment]
@mouad-mahfoud Thanks for suggesting! What libraries did you have in mind for this?

**Comment by Maximization** [comment]
@mouad-mahfoud I've added two categories:

- [HTML Scrapers](https://nodejstoolbox.com/categories/html-scrapers)
- [Web Scraping Frameworks](https://nodejstoolbox.com/categories/web-scraping-frameworks)

Let me know if you're looking for anything else.
