### ISSUE TITLE
Build Systems

### ISSUE THREAD

**Issue by maikofelix47** [Maximization/nodejs-toolbox-catalog#15]
Should JavaScript/Typescript build systems such as Nx(https://nx.dev/),Lerna(https://lerna.js.org/),Turbo(https://turbo.build/) also be added to the categories since they do help manage NodeJs monorepo projects?

**Comment by Maximization** [comment]
@maikofelix47 Yes I think it's good to include them. Good suggestion! Any other you can think of besides these 3?

**Comment by maikofelix47** [comment]
@Maximization Thank you. There are  a good number. Those 3 are the major ones. The other ones include but not limited to 
1. Rush - [https://rushjs.io/](url)
2. Yarn workspaces - [https://classic.yarnpkg.com/en/docs/workspaces/](url)
3. Bit - [https://bit.dev/](url)
4. Oao - [https://github.com/guigrpa/oao](url)
5. Bolt - [https://github.com/boltpkg/bolt](url)

**Comment by Maximization** [comment]
Closed by #16 and live at https://nodejstoolbox.com/categories/build-systems
