### ISSUE TITLE
Rename Web Authentication to Authentication?

### ISSUE THREAD

**Issue by freeborough** [Maximization/nodejs-toolbox-catalog#20]
It's great that you have an authorization section, as that's so often overlooked, but an authentication section would be very welcome.  Things like Passport, Auth.js, and so on.

**Comment by Maximization** [comment]
@freeborough There's a [Web Authentication](https://nodejstoolbox.com/categories/web-authentication) category. Maybe I should rename it to just Authentication? 🤔

**Comment by etroynov** [comment]
@Maximization sounds good
