### ISSUE TITLE
PDF category?

### ISSUE THREAD

**Issue by hyzyla** [Maximization/nodejs-toolbox-catalog#21]
Would you mind to add PDF category with libraries for generating and editing PDF files?

**Comment by Maximization** [comment]
@hyzyla Good suggestion! What libraries do you know of?

**Comment by Maximization** [comment]
Added in https://github.com/Maximization/nodejs-toolbox-catalog/commit/e6395af09334987fee93a4470f72d5cd374cc9bc

Link: https://nodejstoolbox.com/categories/pdf-generation
