### ISSUE TITLE
How is score value calculated?

### ISSUE THREAD

**Issue by rvillane** [Maximization/nodejs-toolbox-catalog#22]
Hi, mine is more a question than an actual issue, I'm curious how is the score value calculated in Node.js Toolbox ?

thanks

**Comment by Maximization** [comment]
Hi, the score is calculated as follows:

((Total NPM downloads / Total NPM downloads of most downloaded library) + ((GitHub stars + (GitHub forks * 5)) / (GitHub stars of most starred library + (Github forks of most forked library * 5)))) / 2
