### ISSUE TITLE
Add faker.js

### ISSUE THREAD

**Issue by soumilroy** [Maximization/nodejs-toolbox-catalog#24]
Faker.js is very useful for testing. Should we add it under `Test Frameworks` or have a separate category?

https://www.npmjs.com/package/@faker-js/faker

**Comment by Maximization** [comment]
Thanks for the suggestion @soumilroy ! I've added a new category and included faker and a few other libraries.

[Random Data Generation](https://nodejstoolbox.com/categories/random-data-generation)
