### ISSUE TITLE
New section: Mono-Repository Tooling

### ISSUE THREAD

**Issue by nf-ssc** [Maximization/nodejs-toolbox-catalog#28]
You could add a new section Mono-Repository Tooling and list tools to manage large-scale mono-repositories. Examples are lerna or turbo-repo.

**Comment by nf-ssc** [comment]
Already listed as `Build Systems`.

**Comment by Maximization** [comment]
@nf-ssc Thanks for suggesting! I should add a search feature so you can search for "lerna" and find the corresponding category.
