### ISSUE TITLE
New category: Image processors 

### ISSUE THREAD

**Issue by Dantescur** [Maximization/nodejs-toolbox-catalog#29]
Maybe adding a cat for image processing, [sharp](https://sharp.pixelplumbing.com/) , [jimp](https://github.com/jimp-dev/jimp)  even [qr code](https://github.com/soldair/node-qrcode) should fit I guess.

**Comment by Maximization** [comment]
@Dantescur Great suggestions! Thank you. I've added two categories: [QR Code Generation](https://nodejstoolbox.com/categories/qr-code-generation) and [Image Processing](https://nodejstoolbox.com/categories/image-processing)
