### ISSUE TITLE
[REQ] New category: CMS

### ISSUE THREAD

**Issue by bakasmarius** [Maximization/nodejs-toolbox-catalog#44]
I would like to see a new category with a list of open-source Node.js CMS (Content Management System) libraries (i.e. Strapi, Keystone, Directus, etc.).
P.S.: I really like the website, I think it's a very good idea 👍

**Comment by Maximization** [comment]
Thank you for the suggestion @bakasmarius . Very good idea. CMS category is now live at: https://nodejstoolbox.com/categories/content-management-systems

If you have any feedback, please let me know.

**Comment by bakasmarius** [comment]
I think the list might be a bit longer... 😅 https://jamstack.org/headless-cms/
I haven't looked into all of them of course, but I think you'll find at least several you can add to the list 😉

**Comment by Maximization** [comment]
@bakasmarius Thank you. I used that list together with this one https://nodecms.guide/ to pick the most popular CMSes
