### ISSUE TITLE
Add `Data Visualization` category

### ISSUE THREAD

**Issue by bakasmarius** [Maximization/nodejs-toolbox-catalog#51]
Some of the examples could be found here:
https://www.geeksforgeeks.org/javascript-libraries-for-data-visualization/
https://github.com/hal9ai/awesome-dataviz?tab=readme-ov-file#javascript-tools

**Comment by Maximization** [comment]
@bakasmarius Thank you for the suggestion. Are these libraries used in the backend in any way, or only in the frontend?

**Comment by bakasmarius** [comment]
> @bakasmarius Thank you for the suggestion. Are these libraries used in the backend in any way, or only in the frontend?

To be honest, I'm not sure because I haven't tried any of them, but my logic says that you cannot "see" a visualization in the backend, so they all must be frontend-related at least somehow 😄 
I suggested this category because I'm planning to try at least one of them in the near future and I often use NodeJsToolbox for selecting the right one 😉

**Comment by Maximization** [comment]
Thanks!

The focus for Node.js Toolbox is the Node.js/backend ecosystem. I'm open to adding categories that are both front- and backend. For frontend focused libraries you can try [Best of JS](https://bestofjs.org/).

**Comment by bakasmarius** [comment]
Ahh, sure, makes sense - I didn't really think about it that way 😅
