### ISSUE TITLE
Request to add Excel Crypto Tool？

### ISSUE THREAD

**Issue by zurmokeeper** [Maximization/nodejs-toolbox-catalog#56]
excel-spreadsheets classified libraries actually do not support encryption and decryption of excel files, you need to use third-party libraries to achieve, such as  [officecrypto-tool](https://www.npmjs.com/package/officecrypto-tool), in fact, if the excel classification of the above libraries can be integrated is better, but these libraries have been no one to maintain or will not be merged with the new PR!

**Comment by Maximization** [comment]
@zurmokeeper Thank you for the suggestion. A library for dealing with encryption/decryption of Excel documents is a great idea. There are not many options in this area. I'll add it to Excel Spreadsheets category for now and if similar libraries appear in the future I'll create a category of its own

**Comment by Maximization** [comment]
Now live at https://nodejstoolbox.com/categories/excel-spreadsheets
