### ISSUE TITLE
Geospatial category

### ISSUE THREAD

**Issue by louwers** [Maximization/nodejs-toolbox-catalog#59]

**Comment by Maximization** [comment]
@louwers Thanks for the suggestion. Do you have an example library that would fit in this category?

**Comment by louwers** [comment]
https://turfjs.org/ comes to mind. https://www.npmjs.com/package/@turf/turf

https://www.npmjs.com/package/geolib seems another popular option

https://www.npmjs.com/package/@maplibre/maplibre-gl-native is a very neat package that allows you to render images of maps (I am a maintainer of the underlying C++ library).

**Comment by Maximization** [comment]
@louwers I've added a Geospatial Analysis with the two libraries you've mentioned: https://nodejstoolbox.com/categories/geospatial-analysis. maplibre-gl-native seems to be frontend/app focused, instead of a backend/Node.js library. If you have any additions let me know.
