### ISSUE TITLE
Add Authentication/Authorization category

### ISSUE THREAD

**Issue by cihad** [Maximization/nodejs-toolbox-catalog#7]
How about Authentication/Authorization?

**Comment by Maximization** [comment]
@cihad Good suggestion! What libraries do you have in mind?

**Comment by Maximization** [comment]
@cihad I've added three new categories:

- [Authorization](https://nodejstoolbox.com/categories/authorization)
- [JSON Web Token (JWT)](https://nodejstoolbox.com/categories/json-web-token)
- [Web Authentication](https://nodejstoolbox.com/categories/web-authentication)

Hope you find them useful! Let me know if you're missing a library.

**Comment by cihad** [comment]
Thank you for adding @Maximization,

I haven't researched yet about these libraries. I will.
