### ISSUE TITLE
Monthly or weekly downloads

### ISSUE THREAD

**Issue by ibeladi-mrsool** [Maximization/nodejs-toolbox-catalog#8]
I think monthly or weekly downloads are far more important than total downloads. Refer to moment and dayjs for example.

**Comment by Maximization** [comment]
@ibrahimBeladi Thanks for the suggestion! How far back would it be useful to see historical downloads?

**Comment by ibeladi-mrsool** [comment]
You are all welcome.
I would say a month should be a fair start.

**Comment by Maximization** [comment]
@ibrahimBeladi I've added weekly downloads charts on each category package. You can now choose to compare packages by score (default) or weekly downloads.

Example: https://nodejstoolbox.com/categories/date-and-time

![historical-downloads](https://github.com/Maximization/nodejs-toolbox-catalog/assets/9811142/b7e94ef0-12c3-43aa-810d-5dfa85a3e18b)
